[build]
  command = "npm run build"
  publish = "dist"
  base = "/"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[context.production]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "18"
