[build]
  base = "/"
  publish = "dist"
  functions = "netlify/functions"
  command = "powershell -Command \"npm install --legacy-peer-deps; npm run build\""

[build.environment]
  NODE_VERSION = "18"
  CI = "true"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

[context.production]
  command = "powershell -Command \"npm install --legacy-peer-deps; npm run build\""
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "18"
  CI = "true"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

[context.deploy-preview]
  command = "powershell -Command \"npm install --legacy-peer-deps; npm run build\""
  publish = "dist"

[context.deploy-preview.environment]
  NODE_VERSION = "18"
  CI = "true"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

[context.branch-deploy]
  command = "powershell -Command \"npm install --legacy-peer-deps; npm run build\""
  publish = "dist"

[context.branch-deploy.environment]
  NODE_VERSION = "18"
  CI = "true"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"
